apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: pipeline-demoapplicatie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pipeline-demoapplicatie
  template:
    metadata:
      labels:
        app: pipeline-demoapplicatie
    spec:
      containers:
      - name: pipeline-demoapplicatie
        image: davidooo/pipeline-demoapplicatie:1.0.0-9
        resources:
          limits:
            memory:"265Mi"
            cpu:"500m"
        ports:
          - containerPort: 8080
        
