apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: pipeline-demoapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pipeline-demoapp
  template:
    metadata:
      labels:
        app: pipeline-demoapp
    spec:
      containers:
      - name: pipeline-demoapp
        image: davidooo/pipeline-demoapplicatie:1.0.0-17
        resources:
          limits:
            memory: "265Mi"
            cpu: "500m"
        ports:
          - containerPort: 8080
        
